### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [lwiniwar/ALE#1]
@lwiniwar What functionalities are offered by this plugin that is not explored in the advanced digitizing toolbar and other digitizing tools provided

**Comment by lwiniwar** [comment]
@NyakudyaA Mostly functions to allow editing of 3D LineStrings. With other tools, the third dimension usually gets lost when editing. It also allows labeling of a "status"-Attribute quite easily.

**Comment by NyakudyaA** [comment]
Can you add more detail to what the plugin does so that I can approve? i.e like what you have said above

**Comment by lwiniwar** [comment]
I added some information in the README.md and in the about section of the metadata file. Please let me know if that's enough. The new version has been uploaded as V1.1 into the QGIS Plugin repo.
