### ISSUE TITLE
Switch from "select" to "Pan tool" while switch layers on TOC (QGIS3)

### ISSUE THREAD

**Issue by Antoviscomi** [lwiniwar/ALE#2]
Hello,
I'm noticed that this plugin It causes automatic switch from "select tool" to "pan tool" on (core bar of) QGIS3 when I switch from the active layer to another in the TOC.
From when I'd unistalled this plugin the hold of the tools had worked fine

best regards

**Comment by lwiniwar** [comment]
thanks for the report. Bug has been fixed :)

**Comment by Antoviscomi** [comment]
Thanks a lot for your job
